version: '3'
services:

  app:
    container_name: l-app
    build:
      context: "./docker"
      dockerfile: "Dockerfile"
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./app:/app
    networks:
      - loveero

  mongo_node:
    container_name: l-mongo-node
    image: node:18.12-alpine
    tty: true
    volumes:
        - ./mongo:/app
    environment:
      - DOC_DB_PROTOCOL
      - DOC_DB_PASS
      - DOC_DB_USER
      - DOC_DB_HOST
    networks:
      - loveero
  mongo:
    container_name: l-mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      TZ: Asia/Tokyo
    networks:
      - loveero
networks:
  loveero:
    driver: "bridge"